
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "_/components/Navbar";
import Footer from "_/components/Footer";
import { ToastContainer } from "react-toastify";
import { SessionProvider } from "next-auth/react";
import WrapperForSessionProvider from "_/components/WrapperForSessionProvider/WrapperForSessionProvider";
import CardtContextProvider from "./_Context/cardtContext";
import { GetUserCart, Getuserwishlist } from "_/API/route.services";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Fresh Cart ",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

const res =  await GetUserCart()
const resWishlist = await Getuserwishlist()

  return (
    <html lang="en">
      <body>
     <CardtContextProvider res={res} reswishlist={resWishlist} >
       <WrapperForSessionProvider>
       <ToastContainer />
        <Navbar />
        {children}
        <Footer />
       </WrapperForSessionProvider>
       
        </CardtContextProvider>

      </body>
    </html>
  );
}
